### ISSUE TITLE
Change - Ctime with every sync

### ISSUE THREAD

**Issue by AlexanderSch90** [juanitomint/nextcloud-client-docker#8]
Is it necessary to rewrite the ctime for every File with every synchronization? This leads to an I / O load ...

```
  File: 2021.pdf
  Size: 120865          Blocks: 241        IO Block: 121344 regular file
Device: 39h/57d Inode: 2061475     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/     smb)   Gid: ( 1000/     smb)
Access: 2021-04-26 12:36:18.000000000 +0200
Modify: 2021-04-26 12:36:18.000000000 +0200
Change: 2021-05-01 23:10:21.311090996 +0200
 Birth: -
```
Thanks!

**Comment by juanitomint** [comment]
sorry for the delay... AFAIK it's the sync client doing it not the docker image

**Comment by DarkShortie** [comment]
I came across the same issue and figured out it's caused by the chown in run.sh https://github.com/juanitomint/nextcloud-client-docker/blob/2938df15158e84ffc519e50938fe5cfac25fa3bd/run.sh#L52

I've commented out those lines, rebuild the image and container and checked the files in my sync directory. ctime is not updated anymore now.

To fix this but still use the defined uid/gid it should be possible to run nextcloudcmd with sudo, but I haven't tested this so far.
